<Project Sdk="Aspire.AppHost.Sdk/13.4.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9b07f823-d659-4ccf-a34e-dc4f1ba5ea11</UserSecretsId>
  </PropertyGroup>

</Project>
